POST http://localhost:3001/api/persons
Content-Type: application/json

{ 
      "id": 0,
      "name": "Kutslsiosx Dominsguezixxi", 
      "number": "040-1234562"
}

### Repeated name POST TEST
POST http://localhost:3001/api/persons
Content-Type: application/json

{ 
      "id": 0,
      "name": "Arto Hellas", 
      "number": "312893712"
}

### Missing name POST TEST
POST http://localhost:3001/api/persons
Content-Type: application/json

{ 
      "id": 0,
      "name": "", 
      "number": "312893712"
}

### Missing number POST TEST
POST http://localhost:3001/api/persons
Content-Type: application/json

{ 
      "id": 0,
      "name": "Supex", 
      "number": ""
}